/**
 * The built-in Corporate Phrase Bingo deck.
 *
 * These are phrases a person could plausibly hear in an ordinary professional
 * meeting — not obscure jargon collected to pad a number, and not anything tied
 * to one company or industry. Kept lowercase on purpose: the card reads as a
 * composed instrument rather than a novelty, and the phrases themselves carry the
 * joke. The list is comfortably larger than the 24 a card needs, so two cards
 * dealt back to back look meaningfully different.
 *
 * Order here is irrelevant — the deck is shuffled before a card is dealt.
 */
export const DEFAULT_PHRASES: readonly string[] = [
  'circle back',
  'take this offline',
  'level-set',
  'double-click',
  'move the needle',
  'low-hanging fruit',
  'north star',
  'bandwidth',
  'leverage',
  'strategic alignment',
  'value-add',
  'best-in-class',
  'synergy',
  'right-size',
  'socialize this',
  'action item',
  'operationalize',
  'boil the ocean',
  'stakeholder buy-in',
  'thought leadership',
  'scalable solution',
  'ecosystem',
  'table this',
  'parking lot',
  'run it up the flagpole',
  'net-net',
  'drill down',
  'touch base',
  'deliverables',
  'key learnings',
  'quick win',
  'pain point',
  'guardrails',
  'swim lane',
  'roadmap',
  'cross-functional',
  'visibility',
  'alignment',
  'business case',
  'going forward',
  'at the end of the day',
  "let's unpack that",
  'put a pin in it',
  'keep me honest',
  '30,000-foot view',
  'granular',
  'cadence',
  'ideate',
  'tiger team',
  'single source of truth',
  'center of excellence',
  'digital transformation',
  'change management',
  'operational excellence',
  'win-win',
  'paradigm shift',
  'game changer',
  'deep dive',
  'ping me',
  'loop you in',
  'in my wheelhouse',
  'secret sauce',
  'raise the bar',
  'table stakes',
  'core competency',
  'value proposition',
  'mission-critical',
  'holistic approach',
  'think outside the box',
  'hard stop',
  'push the envelope',
  'all hands',
  'blue-sky thinking',
  'move the goalposts',
  'herding cats',
  'take it to the next level',
];
